name: CI/CD — Build, Push & Deploy Backend

on:
  push:
    branches:
      - deploy

jobs:

  build-ventas:
    name: Build & Push — API Ventas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y Push imagen Ventas
        uses: docker/build-push-action@v5
        with:
          context: ./back-Ventas_SpringBoot/Springboot-API-REST
          dockerfile: ./back-Ventas_SpringBoot/Springboot-API-REST/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/innovatech-ventas:latest

  build-despachos:
    name: Build & Push — API Despachos
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y Push imagen Despachos
        uses: docker/build-push-action@v5
        with:
          context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
          dockerfile: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/innovatech-despachos:latest

  deploy:
    name: Deploy en EC2
    runs-on: ubuntu-latest
    needs: [build-ventas, build-despachos]

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Deploy via SSH a EC2 (a través de bastion frontend)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          proxy_host: ${{ secrets.EC2_BASTION_HOST }}
          proxy_username: ${{ secrets.EC2_USER }}
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Innovatech_Backend

            git remote set-url origin https://github.com/MatiDroid21/Innovatech_Backend.git

            git pull origin deploy

            cat > .env <<EOF
            DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            EOF

            sudo docker compose pull
            sudo docker compose up -d --remove-orphans
            sudo docker image prune -f